---
- hosts: all
  tasks:
  - name: ensure IIS web server is installed
    win_feature:
      name: Web-Server
      state: present
    when: ansible_os_family == "Windows"
  - name: Deploy htm file
    win_get_url:
      url: https://raw.githubusercontent.com/jbuteraarw/gitty01/master/Index.html
      dest: c:\inetpub\wwwroot\iisstart.htm
      force: no 