---
- hosts: all
  tasks:
  - name: ensure IIS web server is installed
    win_feature:
      name: Web-Server
      state: present
    when: ansible_os_family == "Windows"
  - name: Deploy Index file
    template:
      src: https://github.com/jbuteraarw/gitty01/blob/master/iisstart%2Cj2
      dest: c:\inetpub\wwwroot\iisstart.htm