---
- hosts: all
  tasks:
  - name: ensure IIS web server is installed
    win_feature:
      name: Web-Server
      state: present
    when: ansible_os_family == "Windows"
  - name: Deploy htm file
    win_get_url:
      url: http://github.com/jbuteraarw/gitty01/blob/master/iisstart.j2
      dest: c:\inetpub\wwwroot\iisstart.htm